version: 2
jobs:
    build:
        working_directory: ~/app
        docker:
        - image: circleci/node:9.6
        steps:
        - checkout
        - restore_cache:
            key: v0-install-and-build-cache-{{ .Revision }}
        - run:
            name: Install dependencies
            command: yarn install --pure-lockfile
        - run:
            name: Build project
            command: yarn build:test
        - save_cache:
            key: v0-install-and-build-cache-{{ .Revision }}
            paths:
                - dist
                - node_modules
        - run:
            name: Clean node_modules, test for prod
            command: rm -rf node_modules
        - run:
            name: Install node_modules, test for prod
            command: yarn install --frozen-lockfile
        - run:
            name: Ensure build for prod works
            command: yarn build
        - run:
            name: .only check
            command: |
              if grep -RF --include=*.ts \.only test; then
                exit 1
              else
                exit 0
              fi
    test:
        working_directory: ~/freighthub-http2glacier
        docker:
        - image: circleci/node:9.6
        steps:
        - checkout
        - restore_cache:
            key: v0-install-and-build-cache-{{ .Revision }}
        - run:
            name: Test for circular dependencies
            command: yarn circular
        - run:
            name: Check code correctness
            command: yarn lint
        - run:
            name: Test for complexity over 20 points in any given ts file
            command: yarn complexity
        - run:
            name: Generate code coverage
            command: yarn coverage

workflows:
    version: 2
    build_test_deploy:
        jobs:
        - build
        - test:
            requires:
                - build
